# SOURCE: http://70.0.19.239:8080/2.6?mc=false&kbver=1.17.12-gke.1504&oem=esse&user=015c8ea2-660d-11eb-a2c5-c24e499c7467&b=true&s=%22type%3Dpd-standard%2Csize%3D150%22&kd=type%3Dpd-standard%2Csize%3D150&c=px-cluster-d72c9578-7bb4-4b72-b8eb-f7f7a32419b5&stork=true&lh=true&st=k8s&acr=cluster-c-selector
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: "cluster-c-selector"
  name: px-role
  namespace: portworx
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: "cluster-c-selector"
  name: px-role-binding
  namespace: portworx
subjects:
- kind: ServiceAccount
  name: px-account
  namespace: kube-system
roleRef:
  kind: Role
  name: px-role
  apiGroup: rbac.authorization.k8s.io